import Head from 'next/head'
import Image from 'next/image'
import Body from '../components/Body'
import Footer from '../components/Footer'
import Header from '../components/Header'


export default function Home() {
  return (
    <div className='flex flex-col items-center justify-center h-screen'>
      <Head>
        <title>Google Naveen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* header */}
      <Header/>
      {/* body */}
      <Body/>
      {/* footer */}
      <Footer/>
      </div>
  )
}
